import "./style.css";
import { animate, stagger, inView, scroll, timeline } from "motion";
import Splide from '@splidejs/splide';
new Splide( '#splide-Girltalk' ).mount();
new Splide( '#splide-kreass' ).mount();
new Splide( '#splide-mygame' ).mount();
new Splide( '#splide-customizeme' ).mount();
new Splide( '#splide-vogelius' ).mount();
new Splide( '#splide-madglad' ).mount();
new Splide( '#splide-dfic' ).mount();
import '@splidejs/splide/css';